---
author: "Dave F. Kleinschmidt and T. Florian Jaeger"
title: "What do you expect from an unfamiliar talker?"
output: html_document

---


```{r preamble, message = FALSE, warning = FALSE, error = FALSE, results='hide', echo=FALSE}

knitr::opts_chunk$set(dev = c('svg', 'png', 'pdf'),
                      error = FALSE, warning = FALSE, message = FALSE,
                      results = 'hide', echo = FALSE,
                      cache = TRUE)

library(dplyr)
library(tidyr)
library(magrittr)
library(ggplot2)
library(assertthat)

## data and helper functions
## devtools::install_github('kleinschmidt/phonetic-sup-unsup')
require(supunsup)

data <- supunsup::supunsup_clean %>%
  filter(supCond == 'unsupervised') %>%
  mutate(trueCat = respCategory,
         subjNum = as.numeric(factor(subject)),
         trueCatNum = as.numeric(trueCat),
         respCatNum = as.numeric(respCat))

```

```{r distributions, fig.width=8, fig.height=2}

## prior_stats <- data.frame(category=factor(c('b', 'p')),
##                           mean = c(0, 60),
##                           sd = sqrt(c(14, 254)))

prior_stats <- supunsup::prior_stats %>%
  filter(source == 'kronrod2012')

exposure_stats <- data %>%
  group_by(bvotCond, category=trueCat) %>%
  summarise(mean=mean(vot), sd=sd(vot))

sd_noise = sqrt(82)

stats_to_lhood <- function(stats, noise_sd=sd_noise) {
  stats %>%
    group_by(category, mean, sd) %>%
    do(data.frame(vot=seq(-30, 90, 0.5))) %>%
    ungroup() %>%
    mutate(lhood = dnorm(vot, mean, sqrt(sd^2 + noise_sd^2))) %>%
    select(-mean, -sd)
}

exposure_lhood <- exposure_stats %>%
  group_by(bvotCond) %>%
  do(stats_to_lhood(., sd_noise))

prior_lhood <- prior_stats %>% stats_to_lhood(sd_noise)

data %>%
  group_by(bvotCond, vot) %>%
  filter(subject == first(subject)) %>%
  tally() %>%
  ggplot(aes(x=vot)) +
  geom_bar(stat='identity', aes(y=n, fill=bvotCond)) +
  geom_line(data=prior_lhood, aes(y=lhood*1600, group=category),
            color="black", linetype=2) +
  geom_text(data=data.frame(bvotCond=-10), x = 10, y = 60,
            label = 'Typical Talker',
            color='black', hjust=0, vjust=0.3, size=3) +
  geom_text(data=data.frame(bvotCond=-10), x = 40, y = 50,
            label = 'Exposure\nTalker',
            color=hcl(h=15, c=100, l=65), hjust=0, vjust=0.8, size=3,
            lineheight=1) + 
  facet_grid(.~bvotCond) +
  scale_x_continuous('VOT (ms)') +
  scale_y_continuous('Frequency') +
  scale_fill_discrete('/b/ mean\nVOT') +
  theme(legend.position='none')

```

```{r class-fcns, fig.width=8, fig.height=2}

lhood_to_classification <- function(lhood) {
  lhood %>%
    spread(category, lhood) %>%
    mutate(prob_p = p / (p+b))
}

perfect_learning <- exposure_stats %>%
  group_by(bvotCond) %>%
  do(stats_to_lhood(.)) %>%
  lhood_to_classification

no_learning <- prior_stats %>%
  stats_to_lhood %>%
  lhood_to_classification

prior_bound <- no_learning %>%
  arrange(abs(prob_p - 0.5)) %>%
  filter(row_number() ==1) %$%
  vot


boundaries <- data %>%
  group_by(bvotCond, subject) %>%
  do({ glm(respP ~ vot, family='binomial', data=.) %>%
         broom::tidy() %>%
         select(term, estimate)
  }) %>%
  ungroup() %>%
  spread(term, estimate) %>%
  mutate(boundary = -`(Intercept)` / vot,
         ideal_boundary = as.numeric(as.character(bvotCond)) + 20,
         prior_boundary = prior_bound,
         prop_shift = (boundary-prior_boundary)/(ideal_boundary-prior_boundary))

boundary_summary <- boundaries %>%
  group_by(bvotCond) %>%
  summarise(median_shift_perc = round(100*median(prop_shift)),
            shift_text = paste(median_shift_perc, '%', sep='')) %>%
  filter(bvotCond != 0)                 # basically no shift possible


ggplot(data, aes(x=vot, y=respP, color=bvotCond)) +
  geom_line(aes(group=subject), stat='smooth', 
            method='glm', method.args=list(family='binomial'),
            alpha=0.2) +
  facet_grid(.~bvotCond) +
  geom_line(data=perfect_learning, aes(y=prob_p), group=1, linetype=2, size=1) +
  geom_line(data=no_learning, aes(y=prob_p), group=1, linetype=2, color='black') +
  geom_text(data=data.frame(bvotCond=-10),
            x = 30, y = 0, label = 'Typical\ntalker',
            size = 3.5, hjust=0, vjust = 0, color='black',
            lineheight=1) + 
  geom_text(data=data.frame(bvotCond=-10),
            x = 12, y = 1, label = 'Expo-\nsure',
            size = 3.5, hjust=1, vjust=1, color=hcl(15, c=100, l=65),
            lineheight=1, fontface='bold') + 
  geom_text(data=data.frame(bvotCond=-10),
            x = 90, y = 0.75, label = 'Actual\nlisteners',
            size = 3.5, hjust=1, vjust=1, color=hcl(15, c=100, l=65),
            lineheight=1) + 
  ## geom_text(data=boundary_summary, aes(x=75, y=0.1, label=shift_text), color='black') + 
  theme(legend.position='none') +
  scale_x_continuous('VOT (ms)') +
  scale_y_continuous('Probability /p/ response') + 
  scale_color_discrete('/b/ mean\nVOT')


```

```{r load-samples}

mod_samples <- readRDS('../nips_2015/data/samples_lapsing.rds')

```

```{r inferred-prior-vs-kronrod, fig.width=4, fig.height=3}


samples_to_prior_stats <- function(samples, mean_name='mu_0', sd_name='sigma_0') {
  data.frame(category = c('b', 'p'),
             mean = apply(samples[[mean_name]], 2, mean),
             sd = apply(samples[[sd_name]], 2, mean))
}

mod_prior_lhood <- mod_samples %>%
  samples_to_prior_stats %>%
  stats_to_lhood(noise_sd = 0)

ggplot(mod_prior_lhood, aes(x=vot, y=lhood, group=category)) +
  geom_line(aes(linetype='Inferred\nprior')) +
  geom_line(data=prior_lhood, aes(linetype='Kronrod et\nal. (2012)')) +
  scale_linetype_discrete('Source') +
  scale_x_continuous('VOT (ms)') +
  scale_y_continuous('Likelihood')


```

```{r belief-updating-animation, eval=FALSE}

library(beliefupdatr)

samples_to_nix_params <- function(samples) {
  samples %>%
    samples_to_prior_stats %>%
    transmute(category, mu = mean, sigma2 = sd^2) %>%
    mutate(kappa = mean(samples$kappa_0),
           nu = mean(samples$nu_0))
}

p0 <- samples_to_nix_params(mod_samples) %>%
  group_by(category) %>%
  do(p = {do.call(nix2_params, .)})
  
updated_p <- data %>%
  group_by(bvotCond) %>%
  filter(subject == first(subject)) %>%
  select(vot, trial, bvotCond, trueCat) %>%
  group_by(bvotCond, trueCat) %>%
  summarise(xbar = mean(vot),
            s2 = var(vot)) %>%
  rowwise() %>%
  do(data.frame(., n = seq(0, 200, by=50))) %>%
  left_join(p0, by=c(trueCat='category')) %>%
  mutate(p_updated = list(nix2_update(p=p, xbar=xbar, s2=s2, n=n)))

## likelihood curves
updated_p %>%
  group_by(bvotCond, trueCat, n) %>%
  do({ data_frame(vot = -30:100,
                  lhood = d_nix2_predict(vot, .$p_updated[[1]])) }) %>%
  ggplot(aes(x=vot, y=lhood, color=bvotCond, linetype=trueCat,
             group=paste(bvotCond, trueCat, n))) +
  geom_line() +
  facet_grid(.~n)

## classification functions
updated_p %>%
  group_by(bvotCond, trueCat, n) %>%
  do({ data_frame(vot = -30:100,
                  lhood = d_nix2_predict(vot, .$p_updated[[1]])) }) %>%
  spread(trueCat, lhood) %>%
  mutate(respP = p / (b+p)) %>%
  ggplot(aes(x=vot, y=respP, color=bvotCond,
             group=paste(bvotCond, n))) +
  geom_line() +
  facet_grid(.~n)

  
```

